
var parentDoc : GameObject;
var infoBubble : GameObject;
var infoText : TextMesh;
private var docQuestion : GameObject;
private var soundSwitch = false;
private var soundBank : GameObject;


function Start(){
    docQuestion = GameObject.Find("Card_QuestionDoc");
    parentDoc = transform.parent.gameObject;
    soundBank = GameObject.Find("Sounds");
}

function OnMouseOver(){
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Accom"){
        infoText.text = " Ravensbourne refer students to a variety\n of accommodation providers including\n host families, studios and cluster\n flats. Visit Ravensbourne website\n for more information.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Birth"){
        infoText.text = " Your maintenance fund to support your\n living cost and tuition fee in the UK\n must be under your name, your parent or\n your legal guardian.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Cas"){
        infoText.text = " A CAS is an electronic document issued\n to you by the institution (college,\n school or university) that you have\n chosen to study at. Your CAS will be\n valid for use in a Tier 4 application\n for six months from the date that it\n was generated by your institution.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Confirm"){
        infoText.text = " You should accept your offer by returning\n the course acceptance form. Which can be\n found on the last page of your offer\n letter.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_CopyQual"){
        infoText.text = " You will need to present your original\n educational certificates at enrolment.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_CV"){
        infoText.text = " This is a brief account of your career,\n to showcase your skills and experience\n to Ravensbourne.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Details"){
        infoText.text = " An authorised education agent can fill in\n the application details on the behalf of\n an applicant.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_FeePay"){
        infoText.text = " International students who pay their\n tuition fees in full by 1st September\n 2015​​ ​will receive a 5% discount from\n your total fees.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Finance"){
        infoText.text = " Official financial sponsor as defined by\n UKVI include: Her Majesty's Government,\n the student's home government, the British\n Council or any international organisation,\n international company, university or UK\n independent school.\n\n If you are receiving\n financial support from another type of body\n or organisation, or from your relatives, this\n does not count as official financial\n sponsorship.\n\n Please note that if you only\n receive partial sponsorship, you must\n provide evidence that you have the rest of\n the money required.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Flight"){
        infoText.text = " Once you have your flight details, you\n must inform the  International\n Development Office as soon as possible.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Ielts"){
        infoText.text = " Foundation (equivalent to an overall\n IELTS score of 5.0 with a minimum of 5.0\n in each of the four sub-components)\n\n Undergraduate (equivalent to an overall\n IELTS score of 6.0 with a minimum of 6.0\n in each of the four sub-components)\n\n Postgraduate (equivalent to an overall\n IELTS score of 6.5 with a minimum of 6.0\n in each of the four sub-components)";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Interview"){
        infoText.text = " This can be a skype or face-to-face\n interview.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Offer"){
        infoText.text = " You will need to accept the offer on or\n before the deadline mentioned on your\n offer letter.\n Please check your offer status:\n 1. If youhave been given conditional\n offer, you are therefore required to\n provide the you have met the conditions\n of your offer.\n 2. If you have been given uncodnitional\n offer, you must accept your offer as\n soon as possible in order to secure your\n place and pay the deposit of 50% or full\n course fee on or before the deadline\n given.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_PassCopy"){
        infoText.text = " Please ensure that your passport is valid\n for at least 6 months before the date of\n your Tier 4 visa application, we need\n this copy at the application stage.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_PassPhoto"){
        infoText.text = " You must write your full name on the\n reverse side of your passport photograph\n before submitting it with your visa\n application.\n\nhttps://www.gov.uk/photos-for-passports/\n photo-requirements";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Passport"){
        infoText.text = " You will need to present your current\n passport, when applying for your\n Tier 4 Visa.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_PersBank"){
        infoText.text = " Your financial documents must show that\n the full amount of money that you need\n has been in the account for 28\n consecutive days up to the date of the\n closing balance. This means that the\n account must not have dropped below the\n amount that you need to show at any time\n during the 28 day period. If it does\n your immigration application is likely\n to be refused.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Portfolio"){
        infoText.text = " Your work should cover the whole design\n process: from initial research, through\n concept development to the finished piece.\n If your portfolio is more that 10mb we\n suggest that you use website such as\n Flickr, Youtube or Vimeo and provide us\n with a link.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Quals"){
        infoText.text = " You will need to present your original\n qualifications at enrolment.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Reference"){
        infoText.text = " For UnderGraduate, PostGraduate & \nFurther Education courses.\n Letterheaded paper, If sending the\n reference as an e-mail, send it from the\n e-mail address at the institution or\n organisation you are representing";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Statement"){
        infoText.text = " This is a piece of writing that allows\n you to tell Ravensbourne why you are\n applying and why you should be offered\n a place on the course.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Visa"){
        infoText.text = " For students entering in the UK.\n We recommend that you arrive via a UK\n ‘port of entry’ such as Heathrow,\n Gatwick, Belfast, or Manchester.\n When your visa is issued to you it\n grants you entry clearance to arrive\n in the UK. When you enter a UK port of\n entry your visa will then be stamped by\n an immigration officer granting you leave\n to enter the UK. This stamp is very\n important as it activates your visa.\n If you come via the Republic of Ireland\n you will not receive this stamp and you\n may not be deemed as having a right to\n remain in the UK, and therefore,\n to study.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_VisaApl"){
        infoText.text = " Once you have submitted all the required\n documents and been offered a place at\n Ravensbourne, accepted our offer and\n paid your 50 % tuition deposit, you will be\n issued with a Confirmation of Acceptance\n or Studies (CAS) which you must use for\n your visa application. You can submit a\n Tier 4 visa application no more than 3\n months before the start date of your course.\n You must then complete the application\n form online by visiting visa4UK website,\n pay the application fee and immigration\n surcharge. You must then book an\n appointment at a Visa Application Centre\n to enrol your biometric data and submit a\n printout of your online application along\n with original supporting documents.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_TB"){
        infoText.text = " Added by GB: Students who are residents\n of certian countries are required to have a\n tuberculosis (TB) test taken. You must\n submit the test results with your Tier 4 visa\n application.\n\n Visit the Home Office webiste\n to check if you require a TB test.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_CasApp"){
        infoText.text = " Please complete this form accurately,\n providing details of all UK visa applied for,\n UK and other countries visa refusals, date\n of your last visit to the UK, state whether\n you have any close relatives currently\n living in the UK (eg parents,\n siblings/aunts/uncles etc)";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_OtherBank"){
        infoText.text = " Only your parent(s)/legal guardian is able\n to provide evidence of funds to support\n your studies via a bank statement/bank\n letter. The statement must show the full\n amount of money needed for your studies\n has been in the bank account for 28\n consecutive days up to the date of the\n closing balance ending no more than 31\n days before your application.\n\n The account must not have dropped below\n the amount that you need at any time\n during the 28 day period.\n\n If it does your immigration\n application is likely to be refused.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Police"){
        infoText.text = " Nationals of certain countries are required\n to register with the police. Check if you\n need to register with the police by visiting\n the UKVI website:\n\n https://www.gov.uk/register-with-the-police";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_VisaAppro"){
        infoText.text = " If you visa application is sucessful the UKVI\n will issue you with a short term (30 days\n validity) visa/vignette and a decision letter.\n The decision letter should confirm that you\n have been granted a Tier 4 visa, the full\n length of your visa, where you should collect\n your biometric residence permit and whether\n you need to register with the police. The\n short term visa enables you to travel to the\n UK to collect your biomteric residence permit.\n The biometric residence permit will show the\n full length of the Tier 4 (General) leave your\n were granted to study in the UK(i.e 1 year or\n 3 years). You must collect your biometric\n residence permit within 10 days of arriving in\n the UK.";
    }
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Doc_Ackno"){
        infoText.text = " The course leader will assess your\n application and will decide whether to\n invite you for the academic interview.\n\n At the same time a member of the\n admissions team will contact to you to\n arrange the tier 4 interview.";
    }
   
    if (parentDoc.GetComponent.<Renderer>().sharedMaterial.name == "Card_Stage1_NE_Mdes"){
        infoText.text = " Yo - Stage info!";
    }


    if (parentDoc.name == "Front"){
        if (docQuestion.GetComponent(DocumentQuestion).docProcessing == true){
            infoBubble.GetComponent.<Renderer>().enabled = true;
            infoText.GetComponent.<Renderer>().enabled = true;
            PlaySound();
        }
    }
    else if (parentDoc.name == "NextStage"){
        if (docQuestion.GetComponent(DocumentQuestion).docProcessing == false){
            infoBubble.GetComponent.<Renderer>().enabled = true;
            infoText.GetComponent.<Renderer>().enabled = true;
            PlaySound();
        }
    }
    else{
        if (parentDoc.GetComponent(InventoryClick).mouseToggle == true){
            infoBubble.GetComponent.<Renderer>().enabled = true;
            infoText.GetComponent.<Renderer>().enabled = true;
            PlaySound();
        }
    }

}

function PlaySound(){
    if (soundSwitch == false){
        soundSwitch = true;
        soundBank.GetComponent(AudioSource).clip = soundBank.GetComponent(SoundBank).revealInfo;
        soundBank.GetComponent(AudioSource).Play();
        yield WaitForSeconds(2);
        soundSwitch = false;
    }
}

function OnMouseExit(){
    yield WaitForSeconds (3);
infoBubble.GetComponent.<Renderer>().enabled = false;
infoText.GetComponent.<Renderer>().enabled = false;
}

function Update(){
    if (Input.GetMouseButton(0)){
        infoBubble.GetComponent.<Renderer>().enabled = false;
        infoText.GetComponent.<Renderer>().enabled = false;
    }
}