
var countryToggle : GameObject;
private var soundBank : GameObject;
private var soundSwitch = false;

function Start(){
    countryToggle = GameObject.Find("CountryChoice");
    soundBank = GameObject.Find("Sounds");
}

function PlaySound(){
    if (soundSwitch == false){
        soundSwitch = true;
        soundBank.GetComponent(AudioSource).clip = soundBank.GetComponent(SoundBank).selectionPop;
        soundBank.GetComponent(AudioSource).Play();
        yield WaitForSeconds(2);
        soundSwitch = false;
    }
}

function OnMouseOver(){
if (Input.GetMouseButtonDown(0)){
//selectedGraphic.GetComponent(Image).enabled = !selectedGraphic.GetComponent(Image).enabled;
if (name == "Toggle1") countryToggle.GetComponent(CountryToggle).toggle1Selected = true;
if (name == "Toggle2") countryToggle.GetComponent(CountryToggle).toggle2Selected = true;
if (name == "Toggle3") countryToggle.GetComponent(CountryToggle).toggle3Selected = true;
if (name == "Toggle4") countryToggle.GetComponent(CountryToggle).toggle4Selected = true;
if (name == "Toggle5") countryToggle.GetComponent(CountryToggle).toggle5Selected = true;
if (name == "Toggle6") countryToggle.GetComponent(CountryToggle).toggle6Selected = true;
if (name == "Toggle7") countryToggle.GetComponent(CountryToggle).toggle7Selected = true;
if (name == "Toggle8") countryToggle.GetComponent(CountryToggle).toggle8Selected = true;
if (name == "Toggle9") countryToggle.GetComponent(CountryToggle).toggle9Selected = true;
if (name == "Toggle10") countryToggle.GetComponent(CountryToggle).toggle10Selected = true;
if (name == "Toggle11") countryToggle.GetComponent(CountryToggle).toggle11Selected = true;
if (name == "Toggle12") countryToggle.GetComponent(CountryToggle).toggle12Selected = true;
if (name == "Toggle13") countryToggle.GetComponent(CountryToggle).toggle13Selected = true;
if (name == "Toggle14") countryToggle.GetComponent(CountryToggle).toggle14Selected = true;
if (name == "Toggle15") countryToggle.GetComponent(CountryToggle).toggle15Selected = true;
if (name == "Toggle16") countryToggle.GetComponent(CountryToggle).toggle16Selected = true;
if (name == "Toggle17") countryToggle.GetComponent(CountryToggle).toggle17Selected = true;
if (name == "Toggle18") countryToggle.GetComponent(CountryToggle).toggle18Selected = true;
if (name == "Toggle19") countryToggle.GetComponent(CountryToggle).toggle19Selected = true;
if (name == "Toggle20") countryToggle.GetComponent(CountryToggle).toggle20Selected = true;
if (name == "Toggle21") countryToggle.GetComponent(CountryToggle).toggle21Selected = true;
if (name == "Toggle22") countryToggle.GetComponent(CountryToggle).toggle22Selected = true;
if (name == "Toggle23") countryToggle.GetComponent(CountryToggle).toggle23Selected = true;
if (name == "Toggle24") countryToggle.GetComponent(CountryToggle).toggle24Selected = true;
if (name == "Toggle25") countryToggle.GetComponent(CountryToggle).toggle25Selected = true;
if (name == "Toggle26") countryToggle.GetComponent(CountryToggle).toggle26Selected = true;
if (name == "Toggle27") countryToggle.GetComponent(CountryToggle).toggle27Selected = true;
if (name == "Toggle28") countryToggle.GetComponent(CountryToggle).toggle28Selected = true;
if (name == "Toggle29") countryToggle.GetComponent(CountryToggle).toggle29Selected = true;
if (name == "Toggle30") countryToggle.GetComponent(CountryToggle).toggle30Selected = true;
if (name == "Toggle31") countryToggle.GetComponent(CountryToggle).toggle31Selected = true;
if (name == "Toggle32") countryToggle.GetComponent(CountryToggle).toggle32Selected = true;
if (name == "Toggle33") countryToggle.GetComponent(CountryToggle).toggle33Selected = true;
if (name == "Toggle34") countryToggle.GetComponent(CountryToggle).toggle34Selected = true;
if (name == "Toggle35") countryToggle.GetComponent(CountryToggle).toggle35Selected = true;
if (name == "Toggle36") countryToggle.GetComponent(CountryToggle).toggle36Selected = true;
if (name == "Toggle37") countryToggle.GetComponent(CountryToggle).toggle37Selected = true;
if (name == "Toggle38") countryToggle.GetComponent(CountryToggle).toggle38Selected = true;
if (name == "Toggle39") countryToggle.GetComponent(CountryToggle).toggle39Selected = true;
if (name == "Toggle40") countryToggle.GetComponent(CountryToggle).toggle40Selected = true;
if (name == "Toggle41") countryToggle.GetComponent(CountryToggle).toggle41Selected = true;
if (name == "Toggle42") countryToggle.GetComponent(CountryToggle).toggle42Selected = true;
if (name == "Toggle43") countryToggle.GetComponent(CountryToggle).toggle43Selected = true;
if (name == "Toggle44") countryToggle.GetComponent(CountryToggle).toggle44Selected = true;
if (name == "Toggle45") countryToggle.GetComponent(CountryToggle).toggle45Selected = true;
if (name == "Toggle46") countryToggle.GetComponent(CountryToggle).toggle46Selected = true;
if (name == "Toggle47") countryToggle.GetComponent(CountryToggle).toggle47Selected = true;
if (name == "Toggle48") countryToggle.GetComponent(CountryToggle).toggle48Selected = true;
if (name == "Toggle49") countryToggle.GetComponent(CountryToggle).toggle49Selected = true;
if (name == "Toggle50") countryToggle.GetComponent(CountryToggle).toggle50Selected = true;
if (name == "Toggle51") countryToggle.GetComponent(CountryToggle).toggle51Selected = true;
if (name == "Toggle52") countryToggle.GetComponent(CountryToggle).toggle52Selected = true;
if (name == "Toggle53") countryToggle.GetComponent(CountryToggle).toggle53Selected = true;
if (name == "Toggle54") countryToggle.GetComponent(CountryToggle).toggle54Selected = true;
if (name == "Toggle55") countryToggle.GetComponent(CountryToggle).toggle55Selected = true;
if (name == "Toggle56") countryToggle.GetComponent(CountryToggle).toggle56Selected = true;
if (name == "Toggle57") countryToggle.GetComponent(CountryToggle).toggle57Selected = true;
if (name == "Toggle58") countryToggle.GetComponent(CountryToggle).toggle58Selected = true;
if (name == "Toggle59") countryToggle.GetComponent(CountryToggle).toggle59Selected = true;
if (name == "Toggle60") countryToggle.GetComponent(CountryToggle).toggle60Selected = true;
if (name == "Toggle61") countryToggle.GetComponent(CountryToggle).toggle61Selected = true;
if (name == "Toggle62") countryToggle.GetComponent(CountryToggle).toggle62Selected = true;
if (name == "Toggle63") countryToggle.GetComponent(CountryToggle).toggle63Selected = true;
if (name == "Toggle64") countryToggle.GetComponent(CountryToggle).toggle64Selected = true;
if (name == "Toggle65") countryToggle.GetComponent(CountryToggle).toggle65Selected = true;
if (name == "Toggle66") countryToggle.GetComponent(CountryToggle).toggle66Selected = true;
if (name == "Toggle67") countryToggle.GetComponent(CountryToggle).toggle67Selected = true;
if (name == "Toggle68") countryToggle.GetComponent(CountryToggle).toggle68Selected = true;
if (name == "Toggle69") countryToggle.GetComponent(CountryToggle).toggle69Selected = true;
if (name == "Toggle70") countryToggle.GetComponent(CountryToggle).toggle70Selected = true;
if (name == "Toggle71") countryToggle.GetComponent(CountryToggle).toggle71Selected = true;
if (name == "Toggle72") countryToggle.GetComponent(CountryToggle).toggle72Selected = true;
if (name == "Toggle73") countryToggle.GetComponent(CountryToggle).toggle73Selected = true;
if (name == "Toggle74") countryToggle.GetComponent(CountryToggle).toggle74Selected = true;
if (name == "Toggle75") countryToggle.GetComponent(CountryToggle).toggle75Selected = true;
if (name == "Toggle76") countryToggle.GetComponent(CountryToggle).toggle76Selected = true;
if (name == "Toggle77") countryToggle.GetComponent(CountryToggle).toggle77Selected = true;
if (name == "Toggle78") countryToggle.GetComponent(CountryToggle).toggle78Selected = true;
if (name == "Toggle79") countryToggle.GetComponent(CountryToggle).toggle79Selected = true;
if (name == "Toggle80") countryToggle.GetComponent(CountryToggle).toggle80Selected = true;
if (name == "Toggle81") countryToggle.GetComponent(CountryToggle).toggle81Selected = true;
if (name == "Toggle82") countryToggle.GetComponent(CountryToggle).toggle82Selected = true;
if (name == "Toggle83") countryToggle.GetComponent(CountryToggle).toggle83Selected = true;
if (name == "Toggle84") countryToggle.GetComponent(CountryToggle).toggle84Selected = true;
if (name == "Toggle85") countryToggle.GetComponent(CountryToggle).toggle85Selected = true;
if (name == "Toggle86") countryToggle.GetComponent(CountryToggle).toggle86Selected = true;
if (name == "Toggle87") countryToggle.GetComponent(CountryToggle).toggle87Selected = true;
if (name == "Toggle88") countryToggle.GetComponent(CountryToggle).toggle88Selected = true;
if (name == "Toggle89") countryToggle.GetComponent(CountryToggle).toggle89Selected = true;
if (name == "Toggle90") countryToggle.GetComponent(CountryToggle).toggle90Selected = true;
if (name == "Toggle91") countryToggle.GetComponent(CountryToggle).toggle91Selected = true;
if (name == "Toggle92") countryToggle.GetComponent(CountryToggle).toggle92Selected = true;
if (name == "Toggle93") countryToggle.GetComponent(CountryToggle).toggle93Selected = true;
if (name == "Toggle94") countryToggle.GetComponent(CountryToggle).toggle94Selected = true;
if (name == "Toggle95") countryToggle.GetComponent(CountryToggle).toggle95Selected = true;
if (name == "Toggle96") countryToggle.GetComponent(CountryToggle).toggle96Selected = true;
if (name == "Toggle97") countryToggle.GetComponent(CountryToggle).toggle97Selected = true;
if (name == "Toggle98") countryToggle.GetComponent(CountryToggle).toggle98Selected = true;
if (name == "Toggle99") countryToggle.GetComponent(CountryToggle).toggle99Selected = true;
if (name == "Toggle100") countryToggle.GetComponent(CountryToggle).toggle100Selected = true;
if (name == "Toggle101") countryToggle.GetComponent(CountryToggle).toggle101Selected = true;
if (name == "Toggle102") countryToggle.GetComponent(CountryToggle).toggle102Selected = true;
if (name == "Toggle103") countryToggle.GetComponent(CountryToggle).toggle103Selected = true;
if (name == "Toggle104") countryToggle.GetComponent(CountryToggle).toggle104Selected = true;
if (name == "Toggle105") countryToggle.GetComponent(CountryToggle).toggle105Selected = true;
if (name == "Toggle106") countryToggle.GetComponent(CountryToggle).toggle106Selected = true;
if (name == "Toggle107") countryToggle.GetComponent(CountryToggle).toggle107Selected = true;
if (name == "Toggle108") countryToggle.GetComponent(CountryToggle).toggle108Selected = true;
if (name == "Toggle109") countryToggle.GetComponent(CountryToggle).toggle109Selected = true;
if (name == "Toggle110") countryToggle.GetComponent(CountryToggle).toggle110Selected = true;
if (name == "Toggle111") countryToggle.GetComponent(CountryToggle).toggle111Selected = true;
if (name == "Toggle112") countryToggle.GetComponent(CountryToggle).toggle112Selected = true;
if (name == "Toggle113") countryToggle.GetComponent(CountryToggle).toggle113Selected = true;
if (name == "Toggle114") countryToggle.GetComponent(CountryToggle).toggle114Selected = true;
if (name == "Toggle115") countryToggle.GetComponent(CountryToggle).toggle115Selected = true;
if (name == "Toggle116") countryToggle.GetComponent(CountryToggle).toggle116Selected = true;
if (name == "Toggle117") countryToggle.GetComponent(CountryToggle).toggle117Selected = true;
if (name == "Toggle118") countryToggle.GetComponent(CountryToggle).toggle118Selected = true;
if (name == "Toggle119") countryToggle.GetComponent(CountryToggle).toggle119Selected = true;
if (name == "Toggle120") countryToggle.GetComponent(CountryToggle).toggle120Selected = true;
if (name == "Toggle121") countryToggle.GetComponent(CountryToggle).toggle121Selected = true;
if (name == "Toggle122") countryToggle.GetComponent(CountryToggle).toggle122Selected = true;
if (name == "Toggle123") countryToggle.GetComponent(CountryToggle).toggle123Selected = true;
if (name == "Toggle124") countryToggle.GetComponent(CountryToggle).toggle124Selected = true;
if (name == "Toggle125") countryToggle.GetComponent(CountryToggle).toggle125Selected = true;
if (name == "Toggle126") countryToggle.GetComponent(CountryToggle).toggle126Selected = true;
if (name == "Toggle127") countryToggle.GetComponent(CountryToggle).toggle127Selected = true;
if (name == "Toggle128") countryToggle.GetComponent(CountryToggle).toggle128Selected = true;
if (name == "Toggle129") countryToggle.GetComponent(CountryToggle).toggle129Selected = true;
if (name == "Toggle130") countryToggle.GetComponent(CountryToggle).toggle130Selected = true;
if (name == "Toggle131") countryToggle.GetComponent(CountryToggle).toggle131Selected = true;
if (name == "Toggle132") countryToggle.GetComponent(CountryToggle).toggle132Selected = true;
if (name == "Toggle133") countryToggle.GetComponent(CountryToggle).toggle133Selected = true;
if (name == "Toggle134") countryToggle.GetComponent(CountryToggle).toggle134Selected = true;
if (name == "Toggle135") countryToggle.GetComponent(CountryToggle).toggle135Selected = true;
if (name == "Toggle136") countryToggle.GetComponent(CountryToggle).toggle136Selected = true;
if (name == "Toggle137") countryToggle.GetComponent(CountryToggle).toggle137Selected = true;
if (name == "Toggle138") countryToggle.GetComponent(CountryToggle).toggle138Selected = true;
if (name == "Toggle139") countryToggle.GetComponent(CountryToggle).toggle139Selected = true;
if (name == "Toggle140") countryToggle.GetComponent(CountryToggle).toggle140Selected = true;
if (name == "Toggle141") countryToggle.GetComponent(CountryToggle).toggle141Selected = true;
if (name == "Toggle142") countryToggle.GetComponent(CountryToggle).toggle142Selected = true;
if (name == "Toggle143") countryToggle.GetComponent(CountryToggle).toggle143Selected = true;
if (name == "Toggle144") countryToggle.GetComponent(CountryToggle).toggle144Selected = true;
if (name == "Toggle145") countryToggle.GetComponent(CountryToggle).toggle145Selected = true;
if (name == "Toggle146") countryToggle.GetComponent(CountryToggle).toggle146Selected = true;
if (name == "Toggle147") countryToggle.GetComponent(CountryToggle).toggle147Selected = true;
if (name == "Toggle148") countryToggle.GetComponent(CountryToggle).toggle148Selected = true;
if (name == "Toggle149") countryToggle.GetComponent(CountryToggle).toggle149Selected = true;
if (name == "Toggle150") countryToggle.GetComponent(CountryToggle).toggle150Selected = true;
if (name == "Toggle151") countryToggle.GetComponent(CountryToggle).toggle151Selected = true;
if (name == "Toggle152") countryToggle.GetComponent(CountryToggle).toggle152Selected = true;
if (name == "Toggle153") countryToggle.GetComponent(CountryToggle).toggle153Selected = true;
if (name == "Toggle154") countryToggle.GetComponent(CountryToggle).toggle154Selected = true;
if (name == "Toggle155") countryToggle.GetComponent(CountryToggle).toggle155Selected = true;
if (name == "Toggle156") countryToggle.GetComponent(CountryToggle).toggle156Selected = true;
if (name == "Toggle157") countryToggle.GetComponent(CountryToggle).toggle157Selected = true;
if (name == "Toggle158") countryToggle.GetComponent(CountryToggle).toggle158Selected = true;
if (name == "Toggle159") countryToggle.GetComponent(CountryToggle).toggle159Selected = true;
if (name == "Toggle160") countryToggle.GetComponent(CountryToggle).toggle160Selected = true;
if (name == "Toggle161") countryToggle.GetComponent(CountryToggle).toggle161Selected = true;
if (name == "Toggle162") countryToggle.GetComponent(CountryToggle).toggle162Selected = true;
if (name == "Toggle163") countryToggle.GetComponent(CountryToggle).toggle163Selected = true;
if (name == "Toggle164") countryToggle.GetComponent(CountryToggle).toggle164Selected = true;
if (name == "Toggle165") countryToggle.GetComponent(CountryToggle).toggle165Selected = true;
if (name == "Toggle166") countryToggle.GetComponent(CountryToggle).toggle166Selected = true;
if (name == "Toggle167") countryToggle.GetComponent(CountryToggle).toggle167Selected = true;
if (name == "Toggle168") countryToggle.GetComponent(CountryToggle).toggle168Selected = true;
if (name == "Toggle169") countryToggle.GetComponent(CountryToggle).toggle169Selected = true;
if (name == "Toggle170") countryToggle.GetComponent(CountryToggle).toggle170Selected = true;
if (name == "Toggle171") countryToggle.GetComponent(CountryToggle).toggle171Selected = true;
if (name == "Toggle172") countryToggle.GetComponent(CountryToggle).toggle172Selected = true;
if (name == "Toggle173") countryToggle.GetComponent(CountryToggle).toggle173Selected = true;
if (name == "Toggle174") countryToggle.GetComponent(CountryToggle).toggle174Selected = true;
if (name == "Toggle175") countryToggle.GetComponent(CountryToggle).toggle175Selected = true;
if (name == "Toggle176") countryToggle.GetComponent(CountryToggle).toggle176Selected = true;
if (name == "Toggle177") countryToggle.GetComponent(CountryToggle).toggle177Selected = true;
if (name == "Toggle178") countryToggle.GetComponent(CountryToggle).toggle178Selected = true;
if (name == "Toggle179") countryToggle.GetComponent(CountryToggle).toggle179Selected = true;
if (name == "Toggle180") countryToggle.GetComponent(CountryToggle).toggle180Selected = true;
if (name == "Toggle181") countryToggle.GetComponent(CountryToggle).toggle181Selected = true;
if (name == "Toggle182") countryToggle.GetComponent(CountryToggle).toggle182Selected = true;
if (name == "Toggle183") countryToggle.GetComponent(CountryToggle).toggle183Selected = true;
if (name == "Toggle184") countryToggle.GetComponent(CountryToggle).toggle184Selected = true;
if (name == "Toggle185") countryToggle.GetComponent(CountryToggle).toggle185Selected = true;
if (name == "Toggle186") countryToggle.GetComponent(CountryToggle).toggle186Selected = true;
if (name == "Toggle187") countryToggle.GetComponent(CountryToggle).toggle187Selected = true;
if (name == "Toggle188") countryToggle.GetComponent(CountryToggle).toggle188Selected = true;
if (name == "Toggle189") countryToggle.GetComponent(CountryToggle).toggle189Selected = true;
if (name == "Toggle190") countryToggle.GetComponent(CountryToggle).toggle190Selected = true;
if (name == "Toggle191") countryToggle.GetComponent(CountryToggle).toggle191Selected = true;
if (name == "Toggle192") countryToggle.GetComponent(CountryToggle).toggle192Selected = true;
if (name == "Toggle193") countryToggle.GetComponent(CountryToggle).toggle193Selected = true;
if (name == "Toggle194") countryToggle.GetComponent(CountryToggle).toggle194Selected = true;
if (name == "Toggle195") countryToggle.GetComponent(CountryToggle).toggle195Selected = true;
if (name == "Toggle196") countryToggle.GetComponent(CountryToggle).toggle196Selected = true;
if (name == "Toggle197") countryToggle.GetComponent(CountryToggle).toggle197Selected = true;
if (name == "Toggle198") countryToggle.GetComponent(CountryToggle).toggle198Selected = true;
if (name == "Toggle199") countryToggle.GetComponent(CountryToggle).toggle199Selected = true;
if (name == "Toggle200") countryToggle.GetComponent(CountryToggle).toggle200Selected = true;
if (name == "Toggle201") countryToggle.GetComponent(CountryToggle).toggle201Selected = true;
if (name == "Toggle202") countryToggle.GetComponent(CountryToggle).toggle202Selected = true;
if (name == "Toggle203") countryToggle.GetComponent(CountryToggle).toggle203Selected = true;
if (name == "Toggle204") countryToggle.GetComponent(CountryToggle).toggle204Selected = true;
if (name == "Toggle205") countryToggle.GetComponent(CountryToggle).toggle205Selected = true;
if (name == "Toggle206") countryToggle.GetComponent(CountryToggle).toggle206Selected = true;
if (name == "Toggle207") countryToggle.GetComponent(CountryToggle).toggle207Selected = true;
if (name == "Toggle208") countryToggle.GetComponent(CountryToggle).toggle208Selected = true;
if (name == "Toggle209") countryToggle.GetComponent(CountryToggle).toggle209Selected = true;
if (name == "Toggle210") countryToggle.GetComponent(CountryToggle).toggle210Selected = true;
if (name == "Toggle211") countryToggle.GetComponent(CountryToggle).toggle211Selected = true;
if (name == "Toggle212") countryToggle.GetComponent(CountryToggle).toggle212Selected = true;
if (name == "Toggle213") countryToggle.GetComponent(CountryToggle).toggle213Selected = true;
if (name == "Toggle214") countryToggle.GetComponent(CountryToggle).toggle214Selected = true;
if (name == "Toggle215") countryToggle.GetComponent(CountryToggle).toggle215Selected = true;
if (name == "Toggle216") countryToggle.GetComponent(CountryToggle).toggle216Selected = true;
if (name == "Toggle217") countryToggle.GetComponent(CountryToggle).toggle217Selected = true;
if (name == "Toggle218") countryToggle.GetComponent(CountryToggle).toggle218Selected = true;
if (name == "Toggle219") countryToggle.GetComponent(CountryToggle).toggle219Selected = true;
if (name == "Toggle220") countryToggle.GetComponent(CountryToggle).toggle220Selected = true;
if (name == "Toggle221") countryToggle.GetComponent(CountryToggle).toggle221Selected = true;
if (name == "Toggle222") countryToggle.GetComponent(CountryToggle).toggle222Selected = true;
if (name == "Toggle223") countryToggle.GetComponent(CountryToggle).toggle223Selected = true;
if (name == "Toggle224") countryToggle.GetComponent(CountryToggle).toggle224Selected = true;
if (name == "Toggle225") countryToggle.GetComponent(CountryToggle).toggle225Selected = true;
if (name == "Toggle226") countryToggle.GetComponent(CountryToggle).toggle226Selected = true;
if (name == "Toggle227") countryToggle.GetComponent(CountryToggle).toggle227Selected = true;
if (name == "Toggle228") countryToggle.GetComponent(CountryToggle).toggle228Selected = true;
if (name == "Toggle229") countryToggle.GetComponent(CountryToggle).toggle229Selected = true;
if (name == "Toggle230") countryToggle.GetComponent(CountryToggle).toggle230Selected = true;
if (name == "Toggle231") countryToggle.GetComponent(CountryToggle).toggle231Selected = true;
if (name == "Toggle232") countryToggle.GetComponent(CountryToggle).toggle232Selected = true;
if (name == "Toggle233") countryToggle.GetComponent(CountryToggle).toggle233Selected = true;
if (name == "Toggle234") countryToggle.GetComponent(CountryToggle).toggle234Selected = true;
if (name == "Toggle235") countryToggle.GetComponent(CountryToggle).toggle235Selected = true;
if (name == "Toggle236") countryToggle.GetComponent(CountryToggle).toggle236Selected = true;
if (name == "Toggle237") countryToggle.GetComponent(CountryToggle).toggle237Selected = true;
if (name == "Toggle238") countryToggle.GetComponent(CountryToggle).toggle238Selected = true;
if (name == "Toggle239") countryToggle.GetComponent(CountryToggle).toggle239Selected = true;
if (name == "Toggle240") countryToggle.GetComponent(CountryToggle).toggle240Selected = true;
if (name == "Toggle241") countryToggle.GetComponent(CountryToggle).toggle241Selected = true;
if (name == "Toggle242") countryToggle.GetComponent(CountryToggle).toggle242Selected = true;
if (name == "Toggle243") countryToggle.GetComponent(CountryToggle).toggle243Selected = true;
if (name == "Toggle244") countryToggle.GetComponent(CountryToggle).toggle244Selected = true;
if (name == "Toggle245") countryToggle.GetComponent(CountryToggle).toggle245Selected = true;
if (name == "Toggle246") countryToggle.GetComponent(CountryToggle).toggle246Selected = true;
if (name == "Toggle247") countryToggle.GetComponent(CountryToggle).toggle247Selected = true;
if (name == "Toggle248") countryToggle.GetComponent(CountryToggle).toggle248Selected = true;
if (name == "Toggle249") countryToggle.GetComponent(CountryToggle).toggle249Selected = true;
if (name == "Toggle250") countryToggle.GetComponent(CountryToggle).toggle250Selected = true;

countryToggle.GetComponent(CountryToggle).NewSelection();
PlaySound();
}
//change colour?
}